require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ComposersController do

  # This should return the minimal set of attributes required to create a valid
  # Composer. As you add validations to Composer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all composers as @composers" do
      composer = Composer.create! valid_attributes
      get :index
      assigns(:composers).should eq([composer])
    end
  end

  describe "GET show" do
    it "assigns the requested composer as @composer" do
      composer = Composer.create! valid_attributes
      get :show, :id => composer.id.to_s
      assigns(:composer).should eq(composer)
    end
  end

  describe "GET new" do
    it "assigns a new composer as @composer" do
      get :new
      assigns(:composer).should be_a_new(Composer)
    end
  end

  describe "GET edit" do
    it "assigns the requested composer as @composer" do
      composer = Composer.create! valid_attributes
      get :edit, :id => composer.id.to_s
      assigns(:composer).should eq(composer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Composer" do
        expect {
          post :create, :composer => valid_attributes
        }.to change(Composer, :count).by(1)
      end

      it "assigns a newly created composer as @composer" do
        post :create, :composer => valid_attributes
        assigns(:composer).should be_a(Composer)
        assigns(:composer).should be_persisted
      end

      it "redirects to the created composer" do
        post :create, :composer => valid_attributes
        response.should redirect_to(Composer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved composer as @composer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Composer.any_instance.stub(:save).and_return(false)
        post :create, :composer => {}
        assigns(:composer).should be_a_new(Composer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Composer.any_instance.stub(:save).and_return(false)
        post :create, :composer => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested composer" do
        composer = Composer.create! valid_attributes
        # Assuming there are no other composers in the database, this
        # specifies that the Composer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Composer.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => composer.id, :composer => {'these' => 'params'}
      end

      it "assigns the requested composer as @composer" do
        composer = Composer.create! valid_attributes
        put :update, :id => composer.id, :composer => valid_attributes
        assigns(:composer).should eq(composer)
      end

      it "redirects to the composer" do
        composer = Composer.create! valid_attributes
        put :update, :id => composer.id, :composer => valid_attributes
        response.should redirect_to(composer)
      end
    end

    describe "with invalid params" do
      it "assigns the composer as @composer" do
        composer = Composer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Composer.any_instance.stub(:save).and_return(false)
        put :update, :id => composer.id.to_s, :composer => {}
        assigns(:composer).should eq(composer)
      end

      it "re-renders the 'edit' template" do
        composer = Composer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Composer.any_instance.stub(:save).and_return(false)
        put :update, :id => composer.id.to_s, :composer => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested composer" do
      composer = Composer.create! valid_attributes
      expect {
        delete :destroy, :id => composer.id.to_s
      }.to change(Composer, :count).by(-1)
    end

    it "redirects to the composers list" do
      composer = Composer.create! valid_attributes
      delete :destroy, :id => composer.id.to_s
      response.should redirect_to(composers_url)
    end
  end

end
